services:
  - type: web
    name: your-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn school.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: school.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
